version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: voll_med_api
      POSTGRES_USER: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vollmed:
    build:
      context: .
      dockerfile: Dockerfile
    image: vollmed-api:postgres
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=voll_med_api
      - DB_USERNAME=root
      - DB_PASSWORD=root123
    depends_on:
      - db



