version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: voll_med_api
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: